Webgig\FridgeBundle\Entity\Ingredient:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        item:
            type: object
        amount:
            type: integer
        unit:
            type: string
            length: 255
    lifecycleCallbacks: {  }
